feat (workload): [monitoring] windows dcr for text log collection
mspnp/iaas-baseline pull request #23
Opened 2023-08-03 20:11 UTC by ferantivero

2023-08-03 20:44 UTC, josevarela requested changes
Looks good overall. Including a couple of small suggestions in-line

2023-08-03 20:44 UTC, josevarela commented on infra-as-code/bicep/monitoring.bicep
> +@description('Ensure the managed identity for logs DCR DINE policies is has needed permissions.')
```suggestion
@description('Ensure the managed identity for logs DCR DINE policies has the required permissions.')
```

2023-08-03 20:44 UTC, josevarela commented on infra-as-code/bicep/monitoring.bicep
> +@description('Ensure the managed identity for logs DCR DINE policies is has needed permissions.')
```suggestion
@description('Ensure the managed identity for logs DCR DINE policies has the required permissions.')
```

2023-08-03 20:44 UTC, josevarela commented on infra-as-code/bicep/networking.bicep
>  @description('The spokes\'s regional affinity, must be the same as the hub\'s location. All resources tied to this spoke will also be homed in this region. The network team maintains this approved re
references to the hub and spokes in the baseline seem out of place
```suggestion
@description('Region on which to create the VNnet. All resources tied to this VNnet will also be homed in this region. The region passed as a parameter is assumed to have Availability Zone support.')
```

2023-08-18 19:24 UTC, josevarela requested changes
Looks good. Small spelling correction suggested in-line.

2023-08-18 19:24 UTC, josevarela commented on infra-as-code/bicep/networking.bicep
> +@description('Region on which to create the VNnet. All resources tied to this VNnet will also be homed in this region. The region passed as a parameter is assumed to have Availability Zone support.')
```suggestion
@description('Region on which to create the VNet. All resources tied to this VNet will also be homed in this region. The region passed as a parameter is assumed to have Availability Zone support.')
```

2023-08-28 11:54 UTC, merged

2023-08-28 13:40 UTC, ferantivero commented
actual chained long living merge via https://github.com/mspnp/iaas-baseline/pull/25