topic (diagnostic): [gateway] collect diagnostic settings
mspnp/iaas-baseline pull request #26
Opened 2023-12-01 19:27 UTC by ferantivero

2023-12-01 21:48 UTC, josevarela approved these changes
Looks great!

2023-12-12 14:16 UTC, ckittel requested changes
Consistency recommendations to align with the existing items around it.

2023-12-12 14:16 UTC, ckittel commented on infra-as-code/bicep/gateway.bicep
> +  name: '${appGateway.name}-diagnosticSettings'
```suggestion
  name: 'default'
```

2023-12-12 14:16 UTC, ckittel commented on infra-as-code/bicep/internalloadbalancer.bicep
> +  name: '${internalLoadBalancer.name}-diagnosticSettings'
```suggestion
  name: 'default'
```

2023-12-12 14:16 UTC, ckittel commented on infra-as-code/bicep/gateway.bicep
> +  scope: resourceGroup()
```suggestion
```

2023-12-12 14:16 UTC, ckittel commented on infra-as-code/bicep/internalloadbalancer.bicep
> +  scope: resourceGroup()
```suggestion
```

2023-12-12 22:09 UTC, ckittel approved these changes

2024-01-19 18:57 UTC, merged